# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install nautical && sudo apt update -y && sudo apt install jq -y

      # Runs a set of commands using the runners shell
      - name: Get the number of changes
        id: get-num-changes
        run: |
          output=$(python data/scraper.py -f diff)
          diff=$(jq '.diff' <<<"$output")
          message=$(jq '.message' <<<"$output")
          echo "diff = ${diff}, message = ${message}"
          echo "NUM_DIFF=${diff}" >> $GITHUB_OUTPUT
          echo "DISPLAY_MESSAGE=${message}" >> GITHUB_OUTPUT

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.Custom_Badge }}
          gistID: 7e85f87f1f599809fd45d9ef75e9ef42
          filename: DynamicBuoyBadgeData.json
          label: Buoy Status
          message: ${{ steps.get-num-changes.outputs.DISPLAY_MESSAGE }}
          valColorRange: ${{ steps.get-num-changes.outputs.NUM_DIFF }}
          maxColorRange: 100
          minColorRange: 0
